### ISSUE TITLE
jersey2 client config

### ISSUE THREAD

**Issue by dneves** [irenical/fetchy#14]
Was going to give ```Jersey2Connector``` the option to configure the Client ( to register 'custom' features ) and saw that the ```JacksonFeature``` is already there.

Thing is, what if someone don't want to use ```Jackson```?
Should we keep registering this feature anyway?

@d3x7r0 @tiagosimao

**Comment by d3x7r0** [comment]
I completely forgot about this but yeah, I think I'm 100% behind removing the jackson feature from the jersey2 connector. Since there's now a way to register custom features having a hard dependency on jackson adds more issues than it solves.

I vote to remove the dependency.

**Comment by d3x7r0** [comment]
Since this is merged to master I'll take the liberty of closing the issue.
