### ISSUE TITLE
Discuss v2.0 API

### ISSUE THREAD

**Issue by tiagosimao** [irenical/fetchy#5]
Identify the necessary API sets:
- service search
- service call
- service registration
- load balancing
- call resilience
- others?

Discuss each of the APIs, considering current usage and use-cases.

**Comment by jorgegalveias** [comment]
I suggest fetchy could have a mock module ( `fetchy-mock` ) which would provide one or several mock implementation of the `Fetchy` interface to easy the unit tests on  components that need to use Fetchy.

**Comment by dneves** [comment]
- local service
  a simple interface can be treated as a service - there is no need for discovery/balancer

  ```java
  interface MyService {
    String myMethod( String myArgument );
  }

  class MyServiceImpl implements MyService {
    public String myMethod( String myArgument ) {
      return myArgument;
    }
  }
  ```

- remote service
  when you want to call a thrift/grpc/rest/soap/... service

  Typically, you generate some stubs to the corresponding service and, in the thrift case, you end up with classes like Service.Iface and Service.Client (which extends Service.Iface).

  This are remote services, so you need a way to find a suitable address/port to connect to (service discovery + service balancer).
  Also, sometimes, some services are already balanced, so no service balancer is needed (client side) - although you could run it anyway.

  For service discovery, it should be possible to use any kind of implementation for any service.
  This also means that, for the same service, we may be able to 'find' it in multiple sources (ie, consul, etcd, zookeeper, properties, ...)

  For the balancer, using multiple implementations for the same service makes no sense, as you'd lose any state information. (to be confirmed)



Fetchy v1 example usage:

  ```java
  Fetchy fetchy = new Fetchy();
  fetchy.register( new RemoteServiceFactory( consulNodeDiscovery, randomNodeBalancer ) );
  fetchy.register( new OtherRemoteServiceFactory( someNodeDiscovery, someNodeBalancer ) );

  fetchy.find( "serviceId", Service.class )
    .ifPresent( stub -> stub.call( service -> service.myMethod( "argument" ) ) );
  ```

  It's important to note the service factories and the stub.
  As said above, service factories can use different node discovery/balancer implementations.
  The stub is usefull for controlling the client instance (open/close connections, sync/async, latency/fault tolerance, etc).


Fetchy v2:

  - keep stub;
  - keep service node discovery / service node balancer;
  - change the way services are registered within fetchy, without complicating fetchy's find().

  - it'd be nice not to need service factories, reducing the amount of duplicate code spread across all projects.

  Is fetchy.register()/fetchy.find() needed?
  - fetchy Stub's can be cached so no need to register to do a find after ?

  Is fetchy.find() a good name?
  How complex do we want 'fetchy.find()' to be?

  - usage os java's ServiceLoader for defaults is debatable.

Regarding tests, when you have some class depending on Fetchy, you'd want to mock the services within fetchy, not the fetchy.registe()/find() methods.
So you can have a fetchy instance in your tests, register mock services for each interface your code uses.

**Comment by tiagosimao** [comment]
API concepts post RL discussion:
Service ID: java.lang.String
Service Contract: any class/interface
Node: java.net.URI
Discoverer: implements org.irenical.fetchy.Discoverer
Balancer: implements org.irenical.fetchy.Balancer
Connector: implements org.irenical.fetchy.Connector
Call: implements org.irenical.fetchy.Call

Created branch at https://github.com/irenical/fetchy/tree/v2

**Comment by dneves** [comment]
Regarding this new API,

Node: java.net.URI is not possible. URI cannot be created with an address and a port (it needs a scheme, and other stuff). I'm creating a Node( getAddress(), getPort() ) class.

Connector: the way we defined it
```java
public interface Connector< Node, TYPE_STUB > extends Function< Node, Call< TYPE_STUB > > {
}
```
Prevents a current fetchy feature: the usage of 'local' services: services that do not need a Node to connect to (ie, a simple interface/class). This does not make sense giving a Node to the connector (all its going to do is create a new instance of some class).

- Do we want to allow the creation of 'local' and 'remote' service stubs, or just remote?
(Allowing 'local' services might require an awkward Connector structure)

**Comment by d3x7r0** [comment]
Personally I am against going out of the way to support "local" services. It's easy to fall into that trap and try to cover all possible use cases and end up with what is effectively a poor man's dependency injection framework (and there are already better solutions for that use case).

**Comment by tiagosimao** [comment]
@dneves
I'm not sure whether it is a good idea or not in using URI instead of String, but as of now "local" services are easily covered by a trivial usage of the framework, namely by using null address and no discoverer/balancer.
@d3x7r0 
There is no need to skew neither the concepts nor the implementation in any way to achieve the usecase above. Also it might be quite useful to wrap SDK calls or other code that internally synchronously depends on network activity, so (for now) it's zero cost for potential gain.

Testing said corner cases is quite important though, I added a few.

Currently the v2 branch is still missing (at least): timeout handling, logging, event hookage and javadoc. The test coverage is complete for the current feature set (service registration, node discovery, node balancing, stub connecting, method calling and method fallback).

I think only after missing features development and general API human approval should converting fetchy sub-modules to v2 start.

**Comment by tiagosimao** [comment]
Implemented timeouts using java.util.concurrent.Future with some test conditions still missing.

**Comment by tiagosimao** [comment]
Merged with master
