### ISSUE TITLE
Superfluous try/catch on requests with fallback 

### ISSUE THREAD

**Issue by pr7vinas** [irenical/fetchy#9]
Hi,

I would like to point that when a developer is creating a request and wants to bind a fallback to the given request, if possible, Fetchy should not expose the client exception.

Fetchy is still requesting the developer to wrap it in a try/catch (when the client contract throws some exception), which doesn't make much sense since the developer explicitly said that he wants to handle that exception inside the fallback method.

Here follows an example:

 ```JAVA
try {
    Object response = fetchy
      .createRequest("my-service-id", MyService.Iface.class)
      .callable(client -> client.executeClientServiceMethod())
      .fallback(cause -> null)
      .build()
      .execute();
    return response;
} catch (Exception ex) {
   // unnecessary catch
   LOGGER.error(ex.getMessage());
   return null;
}
```

**Comment by tiagosimao** [comment]
Possible fix in [pr#12](https://github.com/irenical/fetchy/pull/12). Pending review, merge, release.
